version: '2'

OrdererOrgs:
  - Name: Orderer 
    Domain: tokentransfer.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: icici 
    Domain: icici.com 
    EnableNodeOUs: true
    Template: 
      Count: 2
    Users:
      Count: 1
  - Name: sbi 
    Domain: sbi.com 
    EnableNodeOUs: true
    Template: 
      Count: 2
    Users:
      Count: 1
 
